---
title: "HW_2"
author: "0juliat0"
date: "2023-11-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Задание 1
```{r}
library(readr)
library(plotly)
library(ggplot2)
library(rstatix)
library(reshape2)
library(corrplot)
library(pheatmap)
library(stats)
library(gridExtra)
library(umap)

life_expectancy_data <- read_rds("/Users/juliat/Downloads/life_expectancy_data.RDS.rds.rds")
```
Задание 2
```{r}
# 'Life expectancy' vs 'GDP'
p <- plot_ly(data = life_expectancy_data, x = ~GDP, y = ~`Life expectancy`, 
             type = 'scatter', mode = 'markers', 
             color = ~continent, marker = list(size = 10))
p
```
Задание 3
```{r}

# Фильтр данных для стран Африки и Америки
africa_america_data <- life_expectancy_data[life_expectancy_data$continent %in% c("Africa", "Americas"),]

# t-test
test_result <- t_test(`Life expectancy` ~ continent, data = africa_america_data)

# p-value
p_value <- test_result$p
p_value
# Визуализация ggplot2 + rstatix
ggplot(africa_america_data, aes(x = continent, y = `Life expectancy`, fill = continent)) +
  geom_boxplot() +
  geom_jitter(width = 0.2, size = 2, alpha = 0.5) +
  annotate("text", x = 1.5, y = max(africa_america_data$`Life expectancy`), 
           label = paste("p-value:", round(p_value, 3)), size = 5) +
  theme_minimal() +
  labs(title = "Life Expectancy Comparison: Africa vs America", y = "Life Expectancy", x = "Continent")

```
Задание 4
```{r}

# Конвертация data.table в data.frame
life_expectancy_df <- as.data.frame(life_expectancy_data)

# Выбор только числовых столбцов и исключение 'Year'
numeric_data <- life_expectancy_df[sapply(life_expectancy_df, is.numeric)]
numeric_data$Year <- NULL  # исключение 'Year'

# Расчет корреляционной матрицы
cor_matrix <- cor(numeric_data, use = "complete.obs") 

# Корреляционная матрица для ggplot
melted_cor_matrix <- melt(cor_matrix)

# Создание heatmap
ggplot(melted_cor_matrix, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(fill = "Correlation")

# Создание correlogram
corrplot(cor_matrix, method = "circle")

```
Задание 5
```{r}

# Вычисление матрицы расстояний, используя евклидово расстояние
dist_matrix <- dist(numeric_data, method = "euclidean")
# Иерархическая кластеризация
hc <- hclust(dist_matrix, method = "complete")
# Построение дендрограммы
plot(hc)

```
Задание 6
```{r}
# Создание heatmap с иерархической кластеризацией
pheatmap(numeric_data, 
         scale = "row",   
         clustering_distance_rows = "euclidean",
         clustering_distance_cols = "euclidean",
         clustering_method = "complete")

# Кластеры в строках: Дендрограмма в левой части тепловой карты объединяет сходные наблюдения. Если строки представляют разные страны или организации, то страны, расположенные ближе друг к другу на дендрограмме, имеют более схожие профили по всем измеряемым показателям.
# Кластеры в столбцах: Дендрограмма в верхней части объединяет схожие показатели. Например, GDP и GNI расположены близко друг к другу, что говорит о том, что они имеют схожую структуру по всем наблюдениям. Это вполне ожидаемо, поскольку GDP и GNI являются экономическими показателями, которые часто движутся вместе.
# Цвета тепловой карты: Цвета на тепловой карте соответствуют масштабированным значениям показателей. В данном случае, поскольку строки масштабированы , цвета показывают, как значение каждого показателя для данного наблюдения сопоставляется со средним значением для данного показателя. Темно-красный цвет указывает на значения, значительно превышающие среднее значение, а темно-синий - на значения, значительно ниже среднего.
# Показатели, которые постоянно имеют темно-красный цвет во многих наблюдениях, могут быть выше среднего значения в вашем наборе данных, что указывает на потенциальные области, требующие внимания или внимания.
# Показатели, постоянно окрашенные в темно-синий цвет, могут выделять области, в которых результаты наблюдений в целом ниже среднего, что может свидетельствовать об областях, требующих улучшения или вызывающих озабоченность.
# Кластеры показателей или наблюдений могут выявить закономерности, требующие дальнейшего изучения. Например, кластер показателей, связанных со здоровьем, может указывать на группу стран со схожими результатами в области здравоохранения.
```
Задание 7
```{r}

# Выполнить РСА 
pca_result <- prcomp(numeric_data, center = TRUE, scale. = TRUE)

# Сводка результатов PCA
summary(pca_result)

# Построение графика дисперсии
plot(pca_result, type = "l")

# Извлечение оценок (координат главных компонент)
scores <- as.data.frame(pca_result$x)

# ggplot первых двух главных компонент
ggplot(scores, aes(PC1, PC2)) +
  geom_point() +
  xlab(paste("PC1 - ", round(summary(pca_result)$importance[2,1]*100, 1), "%")) +
  ylab(paste("PC2 - ", round(summary(pca_result)$importance[2,2]*100, 1), "%")) +
  theme_minimal()

```
Задание 8
```{r}
# Вывести названия столбцов набора данных
print(colnames(life_expectancy_data))

# Добавить оценки PCA к исходному массиву данны
biplot_data <- cbind(life_expectancy_data, PCA1 = pca_result$x[,1], PCA2 = pca_result$x[,2])

# Создание интерактивного biplot
p <- plot_ly(data = biplot_data, x = ~PCA1, y = ~PCA2, type = 'scatter', mode = 'markers',
             text = ~Country, color = ~continent, colors = 'Set1',
             marker = list(size = 10, opacity = 0.5)) %>%
      layout(title = 'PCA Biplot',
             xaxis = list(title = 'PC1'),
             yaxis = list(title = 'PC2'))

# Вывести график
p

```
Задание 9
```{r}
# Задание 7: Интерпретация результатов РСА-анализа
# Результаты PCA-анализа показывают, что первая главная компонента (PC1) объясняет около 39,88% дисперсии данных, а вторая главная компонента (PC2) - около 11,59%. В совокупности первые две компоненты объясняют более 51,47% дисперсии. Это значительная величина, но она также указывает на то, что в данных есть и другие факторы и измерения, которые вносят вклад в оставшуюся дисперсию.
# Представленная диаграмма распределения отображает дисперсии главных компонент, имея типичную форму "локтя", указывающую на то, что первые несколько компонент объясняют наиболее значительную дисперсию, а последующие компоненты вносят меньший вклад. При принятии решения о том, сколько компонентов оставить, обычно учитывается место расположения этого локтя, предполагая, что компоненты, расположенные за этой точкой, вносят меньший вклад в объяснение дисперсии и могут рассматриваться как шум.
# На биплоте показано, как различные страны (представленные точками) отображаются на первые две главные компоненты. Цветовое кодирование по континентам указывает на возможную кластеризацию по континентам. Например, страны одного и того же континента могут объединяться в кластеры, что говорит о сходстве ожидаемой продолжительности жизни и других переменных, включенных в PCA.
# Задание 8: Интерпретация биплота PCA
# biplot PCA объединяет в себе диаграмму рассеяния оценок первых двух главных компонент с векторами, представляющими нагрузки каждой переменной, которые не видны на общем изображении биплограммы. 
# Интерпретация результатов PCA и биплота
# Результаты PCA свидетельствуют о том, что ВВП, показатели здоровья и другие социально-экономические факторы действительно влияют на продолжительность жизни, но делают это сложными способами, которые не могут быть полностью отражены только географическим положением. Кластеризация точек по континентам свидетельствует о сходстве регионов, однако их перекрытие указывает на сложное взаимодействие различных факторов, влияющих на продолжительность жизни.
# В целом, PCA показывает, что существует несколько ключевых измерений, по которым данные различаются наиболее существенно, и эти измерения, скорее всего, связаны с сочетанием экономических, медицинских и социальных факторов. 
```
Задание 10
```{r}
# Выполние UMAP
umap_result <- umap(numeric_data)
umap_data <- as.data.frame(umap_result$layout)
colnames(umap_data) <- c("UMAP1", "UMAP2")
# Визуализация с использованием ggplot2
ggplot(umap_data, aes(UMAP1, UMAP2)) + 
  geom_point() +
  theme_minimal() +
  labs(title = "UMAP Projection")
# Выполние PCA
pca_result <- prcomp(numeric_data, center = TRUE, scale. = TRUE)
scores <- as.data.frame(pca_result$x)
# Визуализация с использованием ggplot2
ggplot(scores, aes(PC1, PC2)) +
  geom_point() +
  theme_minimal() +
  labs(title = "PCA Projection")

# Распределение точек:
# PCA: Точки в проекции PCA распределяются более равномерно по всему пространству. Это свидетельствует о том, что PCA сохраняет глобальную структуру данных и различия между точками в исходном пространстве.
# UMAP: Точки в проекции UMAP формируют несколько четко различимых кластеров. Это указывает на то, что UMAP лучше отражает локальные структуры и возможно подчеркивает более тонкие группировки в данных.
# Сохранение структуры данных:
# PCA: Как линейный метод, PCA стремится сохранить дистанцию и направление максимальной дисперсии, что может привести к менее очевидной кластеризации, если данные имеют сложную или нелинейную структуру.
# UMAP: UMAP, используя нелинейный подход, часто лучше отображает структуру данных, когда важны локальные отношения, что может быть более информативным для определенных видов анализа данных.
# Интерпретация:
# PCA: Интерпретация PCA может быть более прямолинейной, так как она отражает основные направления вариативности в данных.
# UMAP: Интерпретация результатов UMAP может потребовать более глубокого понимания структуры данных и способа формирования кластеров, так как метод может выявлять сложные нелинейные зависимости.
# Выбор метода:
# Выбор между PCA и UMAP может зависеть от целей анализа. Для понимания глобальных отношений и основных направлений дисперсии, PCA может быть предпочтительнее. Если же важнее выявить скрытые локальные шаблоны или кластеры, UMAP может быть предпочтительнее.

```
Задание 11
```{r}
set.seed(123) # For reproducibility
random_cols <- sample(names(numeric_data), 5)
reduced_data <- numeric_data[ , !(names(numeric_data) %in% random_cols)]

pca_reduced <- prcomp(reduced_data, scale = TRUE)
summary(pca_reduced)


library(stats)

# Function to perform PCA after dropping 5 random columns
perform_pca <- function(data, seed) {
  set.seed(seed)  # Set seed for reproducibility
  cols_to_remove <- sample(colnames(data), 5)  # Randomly select 5 columns
  data_reduced <- data[, !(colnames(data) %in% cols_to_remove)]  # Drop the columns
  pca_result <- prcomp(data_reduced, center = TRUE, scale. = TRUE)  # Perform PCA
  summary(pca_result)  # Summarize the PCA results
}

# Perform PCA three times with different random columns removed
pca1 <- perform_pca(numeric_data, seed = 1)
pca2 <- perform_pca(numeric_data, seed = 2)
pca3 <- perform_pca(numeric_data, seed = 3)

# Print the summaries to compare the results
print(pca1)
print(pca2)
print(pca3)

# Видно, что на каждой итерации PCA наблюдается изменение объясненной дисперсии. Хотя суммарная дисперсия, объясненная компонентами, остается близкой к 1 (или 100%), распределение по отдельным компонентам меняется. Например: доля дисперсии, объясненной первой главной компонентой (PC1), в разных итерациях изменяется от примерно 39% до более чем 45%.
# Суммарная дисперсия, объясненная первыми двумя компонентами, колеблется от 54% до 58%. Эти изменения обусловлены тем, что каждый раз удаляются различные признаки, что приводит к изменению базовой структуры данных, которую отражает PCA. Каждый набор признаков вносит свой вклад в общую дисперсию, и их удаление может перераспределить долю дисперсии, объясняемую каждой главной компонентой.
# Этот эксперимент иллюстрирует чувствительность PCA к конкретному набору признаков, включенных в анализ. Поскольку PCA опирается на дисперсию признаков, удаление различных признаков может существенно повлиять на результаты. Именно поэтому PCA, как и снижение размерности в целом, можно считать несколько нестабильным или чувствительным к изменениям исходных данных.

```
Задание 12
```{r}
numeric_data$africa <- ifelse(life_expectancy_data$continent == "Africa", 1, 0)
numeric_data$oceanic <- ifelse(life_expectancy_data$continent == "Oceania", 1, 0)

pca_dummy <- prcomp(numeric_data[, c("africa", "oceanic")], scale = TRUE)

library(factoextra)
fviz_pca_ind(pca_dummy)

# График представляет собой biplot PCA с двумя измерениями, обозначенными как Dim1 и Dim2, которые, представляют собой первые две главные компоненты. Проценты в метках (58,7% для Dim1 и 41,3% для Dim2) указывают на количество дисперсии, которую каждая главная компонента улавливает из набора данных. Вместе они отражают 100% дисперсии, поскольку в PCA включены только две фиктивные переменные ("Африка" и "Океания"), что позволяет свести данные только к двум измерениям.
# biplot PCA обычно показывает как баллы (преобразованные координаты исходных точек данных в пространстве главных компонент), так и нагрузки (коэффициенты исходных переменных). Однако, поскольку были использованы только фиктивные переменные, biplot не дает возможности для интерпретации, поскольку фиктивные переменные обычно принимают бинарные значения (0 или 1), и их использование в PCA может быть проблематичным.
# Кроме того, PCA - это метод, основанный на непрерывных переменных и предполагающий линейную зависимость между ними. Бинарные переменные, особенно неравномерно распределенные (например, редко встречающаяся "Океания" по сравнению с "Африкой"), могут исказить результаты PCA и сделать интерпретацию главных компонент менее понятной.
# Таким образом, проведенный PCA с фиктивными переменными для континентов отражает всю дисперсию бинарных данных, но не позволяет получить значимое представление о структуре данных, как это было бы при применении традиционного PCA к непрерывным переменным. 
```


