---
title: "R_code_5_2"
author: "0juliat0"
date: "2023-09-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Курс: Введение в автоматизацию обработки данных на R | BIOSTAT 2023/24
Задание: 5.2 Обобщающие функции статистик

```{r}
file_path <- "/Users/juliat/Downloads/numeric_data.rds"
numeric_data <- readRDS(file_path)
```
Mean:
```{r}
mean_value <- mean(numeric_data$Базофилы_E1) 
mean_value # 0.650899
round(mean_value, 2)
```
Standard Deviation:
```{r}
std_deviation <- sd(numeric_data$Базофилы_E1)
std_deviation # 0.3759102
round(std_deviation, 2)
```

Maximum:
```{r}
maximum_value <- max(numeric_data$Эритроциты_E1)
maximum_value # 5.7281
round(maximum_value, 2)
```

Standard Error of the Mean:
```{r}
гемоглобин_е2 <- numeric_data$Гемоглобин_E2
```

SD:
```{r}
sd_гемоглобин_е2 <- sd(гемоглобин_е2)
```

SEM:
```{r}
n <- length(гемоглобин_е2)  # Количество наблюдений
sem_гемоглобин_е2 <- sd_гемоглобин_е2 / sqrt(n)
sem_гемоглобин_е2 # 0.1779345
round(sem_гемоглобин_е2, 2)
```



